return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "awk-language-server",
        "bash-language-server",
        "flake8",
        "gofumpt",
        "goimports",
        "golines",
        "gomodifytags",
        "gopls",
        "gotests",
        "gotestsum",
        "hadolint",
        "iferr",
        "impl",
        "json-lsp",
        "lua-language-server",
        "prettierd",
        "markdownlint",
        "shellcheck",
        "shfmt",
        "solargraph",
        "stylua",
        "terraform-ls",
        "yaml-language-server",
      },
    },
  },
}
